### ISSUE TITLE
way too strict requirements

### ISSUE THREAD

**Issue by sebastian-philipp** [Dev317/streamlit_chromadb_connection#6]
can't install this due to: 

```
The conflict is caused by:
    streamlit-chromadb-connection 1.0.3 depends on onnxruntime==1.16.3
    streamlit-chromadb-connection 1.0.2 depends on onnxruntime==1.16.3
    streamlit-chromadb-connection 1.0.0 depends on onnxruntime==1.16.3
    streamlit-chromadb-connection 0.0.5 depends on onnxruntime==1.16.3

```

Please: massively reduce the version requirements.

* libraries should only define bounds defining the compatible dependency versions
* applications using libraries should have strict version requirements.

**Comment by Dev317** [comment]
Hi @sebastian-philipp thanks for the feedback, do you mind create a PR for the issue?

**Comment by amaxcz** [comment]
@Dev317 Please upgrade your library to the modern stack of all Python libraries so that your library works without issues. A PR request is not enough here; your intervention is needed. Please ensure that it begins to install and work immediately on Python 3.12 and above. So far, I have managed to achieve this by removing the dependency on library versions during the build. But it is not completely smooth at the moment...

It would also be good to update your code so that it starts working properly with the latest version of Chroma, as there were issues when creating a new database.
